name: CivicLens
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: CivicLensDB
    restart: unless-stopped
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DB/create_script.sql:/docker-entrypoint-initdb.d/create_script.sql
  api:
    build:
      context: ./BackendAPI
    container_name: CivicLensAPI
    ports:
      - "8000:8000"
    environment:
      DB_CONN: ${DB_CONN:-}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PGV_CONN: ${DB_PGV_CONN}
      OLLAMA_CONN: ${OLLAMA_CONN}
      PYTHONPATH: /app
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./BackendAPI/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./BackendAPI/requirements.txt
          target: /app/requirements.txt
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  ollama:
    image: ollama/ollama:0.16.0
    ports:
      - "4341:11434"
    volumes:
      - ollamadata:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

volumes:
  pgdata:
  ollamadata:
