name: CivicLens
services:
  db:
    image: postgres:17
    container_name: CivicLensDB
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DB/create_script.sql:/docker-entrypoint-initdb.d/create_script.sql
  api:
    build:
      context: ./BackendAPI
    container_name: CivicLensAPI
    ports:
      - "8000:8000"
    environment:
      DB_CONN: ${DB_CONN}
    develop:
      watch:
        - action: sync
          path: ./BackendAPI/src
          target: /app/src
        - action: rebuild
          path: ./BackendAPI/requirements.txt
          target: /app/requirements.txt
volumes:
  pgdata:
